
spring:
  datasource:
    url: jdbc:h2:mem:concurrency?mode=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
        #        show_sql: true # System.out.println() ?? ??? ??? ??? ?? logging ?? ??
        format_sql: true
        use_sql_comments: false

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.transaction.interceptor: trace
